/** Help text aligned with backend agent & decision logic */

export const ALERT_RISK_HELP = {
  title: 'Alert Risk Score',
  body: 'Score assigned when the alert was generated by the AML rules engine (0–100).',
  rules: [
    '0–30 → Low severity',
    '31–60 → Medium severity',
    '61–79 → High severity',
    '80–100 → Critical severity',
    'Increases when rules fire: large transactions, structuring, high-risk countries, activity spikes',
  ],
};

export const CUSTOMER_RISK_HELP = {
  title: 'Customer Risk Profile',
  body: 'Based on KYC data and cumulative risk from past AML rule triggers.',
  rules: [
    'Low: score 0–30',
    'Medium: score 31–60',
    'High: score 61–100',
    'PEP flag and occupation/country also influence investigation weight',
  ],
};

export const OVERALL_RISK_HELP = {
  title: 'Overall Investigation Risk Score',
  body: 'Combined score (0–100) assigned by the Gemini investigation agent from all specialist findings.',
  rules: [
    'Derived from LLM synthesis of customer, transaction, sanctions, PEP, and media signals',
    'Higher scores indicate stronger suspicion across multiple data sources',
    'Feeds into disposition rules alongside sanctions and confidence thresholds',
    'Capped at 100',
  ],
};

export const DECISION_HELP = {
  title: 'AI Decision & Confidence',
  body: 'Final recommendation from the Gemini investigation agent after all specialist agents complete.',
  rules: [
    'SAR — Confirmed sanctions match (immediate) OR strong evidence of suspicious activity',
    'ESCALATE — Confidence below 65% OR ambiguous multi-factor risk',
    'CLEAR — Low risk with no sanctions, PEP, or adverse media flags',
    'Confidence is 0–1 from the LLM, displayed as a percentage in the UI',
  ],
};

export const PIPELINE_HELP = {
  title: 'AI Agent Pipeline',
  body: 'Eight specialized Gemini ADK agents orchestrate the investigation. Screening agents run in parallel where possible; the investigation agent synthesizes all findings for disposition.',
  rules: [
    '1. Customer Profile → KYC, occupation, country, account age',
    '2. Transaction Analysis → amounts, velocity, spike vs average',
    '3. Sanctions Screening → OFAC, UN, EU, internal watchlists',
    '4. PEP Screening → politically exposed person databases',
    '5. Adverse Media → news & fraud reports',
    '6. Investigation → synthesizes all findings into risk score',
    '7. Decision → CLEAR / ESCALATE / SAR recommendation',
    '8. Report → generates narrative for compliance review',
  ],
};

export const AGENT_HELP: Record<string, { title: string; body: string; rules: string[] }> = {
  customer_analysis: {
    title: 'Customer Profile Agent',
    body: 'Pulls customer KYC, account history, and existing risk classification from the bank database.',
    rules: [
      'Reads: name, occupation, country, PEP flag, risk score/category',
      'Calculates account age from oldest account opening date',
      'Sums balances across all customer accounts',
    ],
  },
  transaction_analysis: {
    title: 'Transaction Analysis Agent',
    body: 'Compares the alert-triggering transaction against the customer\'s historical pattern.',
    rules: [
      'Monthly average = mean volume over past months',
      'Spike multiplier = current transfer ÷ monthly average',
      'High risk: spike ≥ 10× OR transfer ≥ ₹20,00,000',
      'Medium risk: spike ≥ 3× OR transfer ≥ ₹5,00,000',
      'Velocity: Normal (<8 txns/30d), Elevated (8–15), High Frequency (>15)',
    ],
  },
  sanctions_check: {
    title: 'Sanctions Screening Agent',
    body: 'Screens customer name and transaction geography against sanctions & high-risk country lists.',
    rules: [
      'Lists checked: OFAC, UN, EU, Internal Watchlist',
      'Name match against known sanctioned entities → match',
      'High-risk countries: Iran, North Korea, Syria, Afghanistan, Yemen',
      'Transactions to high-risk countries increase match likelihood',
    ],
  },
  pep_check: {
    title: 'PEP Screening Agent',
    body: 'Checks if the customer is a Politically Exposed Person requiring enhanced due diligence.',
    rules: [
      'Databases: World-Check, Dow Jones, Internal PEP List',
      'Matches customer name against PEP registry',
      'Also checks is_pep flag from KYC onboarding',
      'Any PEP match elevates investigation priority',
    ],
  },
  media_analysis: {
    title: 'Adverse Media Agent',
    body: 'Searches public sources for negative news, fraud reports, or regulatory actions linked to the customer.',
    rules: [
      'Matches customer name against adverse media database',
      'Returns article count, titles, sources, and dates',
      'Each article adds weight to overall risk score (+5 pts, max +20)',
    ],
  },
  investigation: {
    title: 'Investigation Synthesis Agent',
    body: 'Gemini-powered agent that synthesizes all prior findings into a narrative and risk assessment.',
    rules: [
      'Receives structured outputs from all specialist agents',
      'Produces overall risk score and risk factor list',
      'Generates investigation narrative for compliance review',
    ],
  },
  decision: {
    title: 'Decision Agent',
    body: 'Gemini applies AML disposition rules to specialist findings and synthesis.',
    rules: [
      'SAR if sanctions match confirmed',
      'ESCALATE if confidence < 65% or evidence is ambiguous',
      'CLEAR when no significant risk indicators remain',
      'Outputs CLEAR / ESCALATE / SAR with confidence score',
    ],
  },
  report: {
    title: 'Report Agent',
    body: 'Generates a human-readable investigation summary for compliance records and case files.',
    rules: [
      'Includes customer profile, transaction analysis, screening results',
      'States risk factors, decision, confidence, and recommendation',
      'SAR cases also generate a draft SAR narrative',
    ],
  },
};

export const CONFIDENCE_HELP = {
  title: 'Confidence Score',
  body: 'How strongly the Gemini investigation agent supports its disposition (0–100% in UI).',
  rules: [
    'SAR with sanctions match → high confidence (~95%)',
    'ESCALATE when confidence < 65% regardless of other signals',
    'CLEAR when risk indicators are absent and confidence is sufficient',
    'Derived from LLM assessment of corroborating evidence',
  ],
};
